version: "3.9"
services:
  system-service:
    image: jonasdeweerdt/api-ccs2-projecthosting
    ports:
      - "8000:8000"
    volumes:
      - sqlite_useritems_volume:/code/sqlitedb

volumes:
  sqlite_useritems_volume:
